title: "Kelly's Writing Portfolio"
author: "Kelly"
description: "Flash fiction, nonfiction, experiments, and stories of resonance."

theme: minima
baseurl: "" # leave blank unless using a subfolder
url: "https://kwhms.github.io"

markdown: kramdown
plugins:
  - jekyll-feed

collections:
  early_reader:
    output: true
    permalink: /early_reader/:path/
  flash_fiction:
    output: true
    permalink: /flash_fiction/:path/
  nonfiction:
    output: true
    permalink: /nonfiction_blog/:path/
  prompts:
    output: true
    permalink: /prompts/:path/


