title: Kelly's Writing Portfolio
theme: minima
plugins:
  - jekyll-feed

exclude:
  - README.md
  - .gitignore
  - drafts/
  - unused/
  - fiction_early_reader_gal/
  - fiction_flash_bffa/
  - fiction_flash_reedsy/
  - fiction_flash_sixwords/
  - nonficion_blog/

collections:
  prompts_freewrite:
    output: true
    permalink: /blog/:path/

defaults:
  - scope:
      path: "_flash_fiction"
    values:
      layout: default

